<%@ Page Title="" Language="C#" MasterPageFile="~/masterpage.Master" AutoEventWireup="true" CodeBehind="about.aspx.cs" Inherits="offlineproject.about" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p style="font-size: 18px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        The university has its campus in<span class="Apple-converted-space">&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Dwarka_Sub_City" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Dwarka Sub City">Dwarka</a><span class="Apple-converted-space">&nbsp;</span>being recently shifted from Kashmere Gate. It is a new campus and spread over an area of 60 acres where a still considerable portion is under construction. On Dwarka campus, the university is running 10 schools and imparting professional education to more than 3000 graduate and post-graduate students.</p>
    <p style="font-size: 18px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        Kashmere Gate campus has been solely acquired by Indira Gandhi Institute of Technology and<span class="Apple-converted-space">&nbsp;</span><a href="https://en.wikipedia.org/wiki/Ambedkar_University_Delhi" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Ambedkar University Delhi">Ambedkar University</a>. With an aim to provide &quot;<a class="mw-redirect" href="https://en.wikipedia.org/wiki/Research_and_Development" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Research and Development">Research and Development</a>&quot; facilities of international standards, the university has decided to set up an Institute of Information Technology in Surajmal Vihar,<span class="Apple-converted-space">&nbsp;</span><a href="https://en.wikipedia.org/wiki/East_Delhi" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="East Delhi">East Delhi</a>. For this purpose it has acquired 19 acres (77,000&nbsp;m<sup style="line-height: 1; font-size: 11.1999998092651px;">2</sup>) 
        of land on which the construction is likely to start very soon.</p>
</asp:Content>
