<%@ Page Title="" Language="C#" MasterPageFile="~/masterpage.Master" AutoEventWireup="true" CodeBehind="info.aspx.cs" Inherits="offlineproject.info" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p align="justify" style="color: rgb(0, 0, 0); font-family: Tahoma, Helvetica, sans-serif; font-size: 22px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        National University, &#39;A&#39; Grade accreditation with NAAC, established by Government of NCT of Delhi under the provisions of National University Act, 1998 read with its Amendment in 1999.</p>
    <p align="justify" style="color: rgb(0, 0, 0); font-family: Tahoma, Helvetica, sans-serif; font-size: 22px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <b>Vision:</b><span class="Apple-converted-space">&nbsp;</span>“The University will stimulate both the hearts and minds of scholars, empower them to contribute to the welfare of society at large; train them to adopt themselves to the changing needs of the economy; advocate them for cultural leadership to ensure peace, harmony and prosperity for all.”</p>
    <p align="justify" style="color: rgb(0, 0, 0); font-family: Tahoma, Helvetica, sans-serif; font-size: 22px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <b>Mission:</b>“National University shall strive hard to provide a market oriented professional education to the student community of India in general and of Delhi in particular, with a view to serving the cause of higher education as well as to meet the needs of the Indian industries by promoting establishment of colleges and Schools of Studies as Centres of Excellence in emerging areas of education with focus on professional education in disciplines of engineering, technology, medicine, education, pharmacy, nursing, law, etc.”</p>
    <br class="Apple-interchange-newline" />
</asp:Content>
